#!/bin/bash

set -e

if [ "$1" = "configure" ] ; then
	echo -n "modprobing fuse: "
	modprobe fuse
	echo "done"
	
	echo -n "add fuse to /etc/modules: "
	if [ "X`cat /etc/modules | grep fuse`" == "X" ]; then
		echo "fuse" >> /etc/modules
		echo "done"
	else
		echo "not needed, already exists"
	fi

	echo -n "add i2c-dev to /etc/modules: "
	if [ "X`cat /etc/modules | grep i2c-dev`" == "X" ]; then
		echo "i2c-dev" >> /etc/modules
		echo "done"
	else
		echo "not needed, already exists"
	fi

	echo -n "looking for raspi-blacklist.conf: "
	if [[ -f /etc/modprobe.d/raspi-blacklist.conf ]]; then
		echo "found it, removing i2c from blacklist"
		sed -i -e 's/#blacklist i2c-bcm2708/blacklist i2c-bcm2708/g' /etc/modprobe.d/raspi-blacklist.conf
		sed -i -e 's/blacklist i2c-bcm2708/#blacklist i2c-bcm2708/g' /etc/modprobe.d/raspi-blacklist.conf
	else
		echo "not found"
	fi

	echo -n "create /mnt/1wire: "
	if [ ! -d /mnt/1wire ]; then
		mkdir -p /mnt/1wire
		echo "done"
	else
		echo "not needed, already exists"
	fi

	# removes left-over upstart script when upgrading,
	# can be removed later when all clients have upgraded
	# to using /etc/init.d/owfs
	rm -f /etc/init/owfs.conf

	update-rc.d owfsd defaults 97

	echo "starting owfs"
	/etc/init.d/owfsd start
fi

exit 0
