#!/bin/bash

set -e

if [ "$1" = "configure" ] ; then
	echo -n "modprobing fuse: "
	modprobe fuse
	echo "done"
	
	echo -n "add fuse to /etc/modules: "
	if [ "X`cat /etc/modules | grep fuse`" == "X" ]; then
		echo "fuse" >> /etc/modules
		echo "done"
	else
		echo "not needed, already exists"
	fi
	
	echo -n "create /mnt/1wire: "
	if [ ! -d /mnt/1wire ]; then
		mkdir -p /mnt/1wire
		echo "done"
	else
		echo "not needed, already exists"
	fi

	# removes left-over upstart script when upgrading,
	# can be removed later when all clients have upgraded
	# to using /etc/init.d/owfs
	rm -f /etc/init/owfs.conf

	update-rc.d owfsd defaults 97

	echo "starting owfs"
	/etc/init.d/owfsd start
fi

exit 0
