#!/bin/bash

set -e

if [ "$1" = "install" ] ; then
	echo "first install, no service to stop"
fi

if [ "$1" = "upgrade" ] ; then
	echo "stopping owfs"
	set +e
	service owfs stop > /dev/null 2&>1
	set -e
fi

exit 0
