#!/bin/bash

set -e

if [ "$1" = "install" ] ; then
	echo "first install, no service to stop"
fi

if [ "$1" = "upgrade" ] ; then
	echo "stopping owfs"
	if [ "X`service owfs status | grep running`" != "X" ]; then
		service owfs stop
	fi
fi

exit 0
