#!/bin/bash

set -e

if [ "$1" = "remove" ] ; then
	set +e
	service owfs stop > /dev/null 2&>1
	set -e
	sed '/fuse/d' /etc/modules > /etc/modules.new
	mv /etc/modules.new /etc/modules
	rm -f /etc/init/owfs.conf
	rm -rf /mnt/1wire
fi

exit 0
