#!/bin/bash

set -e

if [ "$1" = "configure" ] ; then
	echo -n "creating /etc/tellstick.conf: "
	if [ ! -f /etc/tellstick.conf ]; then
		echo "user = \"nobody\"
group = \"plugdev\"
ignoreControllerConfirmation = \"false\"" > /etc/tellstick.conf
		chown root:plugdev /etc/tellstick.conf
		chmod 664 /etc/tellstick.conf
		echo "done"
	else
		echo "not needed, already exists"
	fi

	echo -n "creating /var/state/telldus-core.conf: "
	if [ ! -f /var/state/telldus-core.conf ]; then
		mkdir -p /var/state
		touch /var/state/telldus-core.conf
		chown root:plugdev /var/state/telldus-core.conf
		chmod 666 /var/state/telldus-core.conf
	else
		echo "not needed, already exists"
	fi

	if [ ! -f /etc/rc3.d/S98telldusd ]; then
		# The rc3.d S98telldusd does not exist, make sure we don't
		# have a left-over S98telldusd in rc2.d which prevents
		# update-rc.d from adding symlinks to all runlevels
		# (check can be removed when all running servers are
		#  updated)
		rm -f /etc/rc2.d/S98telldusd	
	fi	
	
        update-rc.d telldusd defaults 98

	echo -n "starting telldusd: "
	/etc/init.d/telldusd start
	echo "done"
fi

exit 0
