#!/bin/bash

set -e

if [ "$1" = "remove" ] ; then
	echo -n "stopping telldusd: "
	/etc/init.d/telldusd stop
	echo "done"

	update-rc.d telldusd remove

	echo -n "removing /etc/tellstick.conf: "
	rm -rf /etc/tellstick.conf
	echo "done"
fi

exit 0
